name: barangay_census_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: 3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Icons and visuals
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2

  # Charts and visualizations
  syncfusion_flutter_charts: ^26.1.44
  fl_chart: ^0.65.0

  # Database
  mysql1: ^0.20.0

  # file picker
  file_picker: ^10.3.3

  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Recommended lints for good coding practices

flutter:
  uses-material-design: true

  assets:
    - assets/images/
